version: "3.3"

services:
  api-php:
    build: ./api-php/
    volumes:
      - ./api-php/src:/var/www/html
    ports:
      - 8000:8080
    networks:
      - backend
  api-node:
    build: ./api-node/
    volumes:
      - ./api-node/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8001:8001
    command: npm start
    networks:
      - backend
  api-python:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.7-alpine3.8
    volumes:
      - ./api-python/app:/app
    ports:
      - 8002:80
    command: ["/start-reload.sh"]
    networks:
      - backend
  proxy:
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - backend

networks:
  backend:
    driver: "bridge"