version: "3.3"

services:
  api-php:
    build: ./api-php/
    volumes:
      - ./api-php/src:/var/www/html
    ports:
      - 8000:8080
    networks:
      - backend
  api-node:
    build: ./api-node/
    volumes:
      - ./api-node/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8001:8001
    command: npm start
    networks:
      - backend

networks:
  backend:
    driver: "bridge"