version: "3.3"

services:
  api-php:
    build: ./api-php/
    volumes:
      - ./api-php/src:/var/www/html
    ports:
      - 8000:8080
    networks:
      - backend
  api-python:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.7-alpine3.8
    volumes:
      - ./api-python/app:/app
    ports:
      - 8001:80
    command: ["/start-reload.sh"]
    networks:
      - backend

networks:
  backend:
    external: true